/**
 * Generates backgrounds.raster.ts. Run whenever a background marked `raster`
 * is added or changed:  npx tsx src/scripts/gen-raster.ts
 */
import { chromium } from 'playwright';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { BACKGROUNDS } from '../resume/backgrounds';

// 1x = 816x1056, exactly the CSS size it is painted at. 2x was crisper but
// tripled the file, and these are soft textures behind text rather than
// artwork -- a resume gets emailed, so the bytes matter more than the edge.
const SCALE = 1;
const WIDTH = 816;
const HEIGHT = 1056;
// High enough that a soft glow shows no banding or blocking behind text.
const JPEG_QUALITY = 90;

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', args: ['--no-sandbox'] })
    .catch(() => chromium.launch({ args: ['--no-sandbox'] }));
  const page = await browser.newPage({
    viewport: { width: WIDTH, height: HEIGHT }, deviceScaleFactor: SCALE,
  });

  const out: Record<string, string> = {};
  for (const def of BACKGROUNDS) {
    if (!def.raster) continue;
    const jpeg = def.raster.format === 'jpeg';
    // A PNG is captured on a transparent page and keeps its alpha, so it sits
    // on whatever is under it. A JPEG has no alpha, so it is captured over the
    // page colour it will be shown on and carries that colour with it.
    const under = jpeg ? (def.base ?? '#ffffff') : 'transparent';
    await page.setContent(
      `<html><head><style>html,body{margin:0;padding:0;background:${under}}
       .page{width:${WIDTH}px;height:${HEIGHT}px}${def.css}</style></head><body><div class="page"></div></body></html>`,
      { waitUntil: 'domcontentloaded' },
    );
    const clip = { x: 0, y: 0, width: WIDTH, height: HEIGHT };
    const buf = jpeg
      ? await page.screenshot({ clip, type: 'jpeg', quality: JPEG_QUALITY })
      : await page.screenshot({ clip, omitBackground: true });
    out[def.key] = `data:image/${def.raster.format};base64,${buf.toString('base64')}`;
    console.log(`  ${def.key.padEnd(18)} ${(buf.length / 1024).toFixed(0).padStart(5)} KB ${def.raster.format}`);
  }
  await browser.close();

  const body = Object.entries(out)
    .map(([k, v]) => `  '${k}':\n    '${v}',`)
    .join('\n');
  writeFileSync(
    join(__dirname, '..', 'resume', 'backgrounds.raster.ts'),
    `/* GENERATED by gen-raster.ts -- do not edit by hand.
 *
 * One pre-rendered image for every background that cannot go into a PDF as
 * vector drawing. Two reasons put a pattern here. A repeated shape is written
 * once per repetition when Chromium prints, which took some of these to
 * between 400 KB and 3.3 MB on a three-page resume. And a CSS gradient is
 * written in a form pdf.js draws wrongly. As a single ${SCALE}x image each is one
 * draw that every viewer renders alike. Regenerate with:
 *   npx tsx src/scripts/gen-raster.ts
 */
export const RASTER: Record<string, string> = {
${body}
};
`,
    'utf-8',
  );
  const total = Object.values(out).reduce((n, v) => n + v.length, 0);
  console.log(`\nwrote src/resume/backgrounds.raster.ts  (${Object.keys(out).length} images, ${(total / 1024).toFixed(0)} KB of base64)`);
})().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
