/** Generates backgrounds.raster.ts — run when a heavy pattern changes. */
import { chromium } from 'playwright';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { BACKGROUNDS } from '../resume/backgrounds';

const HEAVY = ['dot-flow', 'dot-grid', 'halftone', 'confetti', 'hexagon', 'circuit', 'scales', 'waves'];
// 1x = 816x1056, exactly the CSS size it is painted at. 2x was crisper but
// tripled the file, and these are soft textures behind text rather than
// artwork -- a resume gets emailed, so the bytes matter more than the edge.
const SCALE = 1;

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', args: ['--no-sandbox'] })
    .catch(() => chromium.launch({ args: ['--no-sandbox'] }));
  const page = await browser.newPage({
    viewport: { width: 816, height: 1056 }, deviceScaleFactor: SCALE,
  });

  const out: Record<string, string> = {};
  for (const key of HEAVY) {
    const def = BACKGROUNDS.find((b) => b.key === key);
    if (!def) throw new Error(`no such background: ${key}`);
    // Paint the layer alone on a transparent page, then capture it.
    await page.setContent(
      `<html><head><style>html,body{margin:0;padding:0;background:transparent}
       .page{width:816px;height:1056px}${def.css}</style></head><body><div class="page"></div></body></html>`,
      { waitUntil: 'domcontentloaded' },
    );
    const buf = await page.screenshot({
      clip: { x: 0, y: 0, width: 816, height: 1056 }, omitBackground: true,
    });
    out[key] = `data:image/png;base64,${buf.toString('base64')}`;
    console.log(`  ${key.padEnd(12)} ${(buf.length / 1024).toFixed(0).padStart(5)} KB png`);
  }
  await browser.close();

  const body = Object.entries(out)
    .map(([k, v]) => `  '${k}':\n    '${v}',`)
    .join('\n');
  writeFileSync(
    join(__dirname, '..', 'resume', 'backgrounds.raster.ts'),
    `/* GENERATED by gen-raster.ts -- do not edit by hand.
 *
 * Pre-rendered PNGs for the patterns whose geometry cannot be expressed as a
 * CSS gradient. Chromium flattens a repeated vector into one drawing operation
 * per repetition when printing, which took these to between 400 KB and 3.3 MB
 * on a three-page resume. As a single ${SCALE}x PNG each is one image and one
 * draw. Regenerate with:  npx tsx src/scripts/gen-raster.ts
 */
export const RASTER: Record<string, string> = {
${body}
};
`,
    'utf-8',
  );
  const total = Object.values(out).reduce((n, v) => n + v.length, 0);
  console.log(`\nwrote src/resume/backgrounds.raster.ts  (${(total / 1024).toFixed(0)} KB of base64)`);
})().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
